// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/ordervalidation"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// OrderValidationDelete is the builder for deleting a OrderValidation entity.
type OrderValidationDelete struct {
	config
	hooks    []Hook
	mutation *OrderValidationMutation
}

// Where appends a list predicates to the OrderValidationDelete builder.
func (ovd *OrderValidationDelete) Where(ps ...predicate.OrderValidation) *OrderValidationDelete {
	ovd.mutation.Where(ps...)
	return ovd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ovd *OrderValidationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ovd.sqlExec, ovd.mutation, ovd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ovd *OrderValidationDelete) ExecX(ctx context.Context) int {
	n, err := ovd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ovd *OrderValidationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ordervalidation.Table, sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt))
	if ps := ovd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ovd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ovd.mutation.done = true
	return affected, err
}

// OrderValidationDeleteOne is the builder for deleting a single OrderValidation entity.
type OrderValidationDeleteOne struct {
	ovd *OrderValidationDelete
}

// Where appends a list predicates to the OrderValidationDelete builder.
func (ovdo *OrderValidationDeleteOne) Where(ps ...predicate.OrderValidation) *OrderValidationDeleteOne {
	ovdo.ovd.mutation.Where(ps...)
	return ovdo
}

// Exec executes the deletion query.
func (ovdo *OrderValidationDeleteOne) Exec(ctx context.Context) error {
	n, err := ovdo.ovd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ordervalidation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ovdo *OrderValidationDeleteOne) ExecX(ctx context.Context) {
	if err := ovdo.Exec(ctx); err != nil {
		panic(err)
	}
}
