// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/order"
	"github.com/mikestefanello/pagoda/ent/ordervalidation"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/user"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetStartTime sets the "start_time" field.
func (ou *OrderUpdate) SetStartTime(t time.Time) *OrderUpdate {
	ou.mutation.SetStartTime(t)
	return ou
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStartTime(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetStartTime(*t)
	}
	return ou
}

// SetEndTime sets the "end_time" field.
func (ou *OrderUpdate) SetEndTime(t time.Time) *OrderUpdate {
	ou.mutation.SetEndTime(t)
	return ou
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableEndTime(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetEndTime(*t)
	}
	return ou
}

// SetDepartureStation sets the "departure_station" field.
func (ou *OrderUpdate) SetDepartureStation(s string) *OrderUpdate {
	ou.mutation.SetDepartureStation(s)
	return ou
}

// SetNillableDepartureStation sets the "departure_station" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDepartureStation(s *string) *OrderUpdate {
	if s != nil {
		ou.SetDepartureStation(*s)
	}
	return ou
}

// SetArrivalStation sets the "arrival_station" field.
func (ou *OrderUpdate) SetArrivalStation(s string) *OrderUpdate {
	ou.mutation.SetArrivalStation(s)
	return ou
}

// SetNillableArrivalStation sets the "arrival_station" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableArrivalStation(s *string) *OrderUpdate {
	if s != nil {
		ou.SetArrivalStation(*s)
	}
	return ou
}

// SetIDNumber sets the "id_number" field.
func (ou *OrderUpdate) SetIDNumber(s string) *OrderUpdate {
	ou.mutation.SetIDNumber(s)
	return ou
}

// SetNillableIDNumber sets the "id_number" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableIDNumber(s *string) *OrderUpdate {
	if s != nil {
		ou.SetIDNumber(*s)
	}
	return ou
}

// SetPhoneNumber sets the "phone_number" field.
func (ou *OrderUpdate) SetPhoneNumber(s string) *OrderUpdate {
	ou.mutation.SetPhoneNumber(s)
	return ou
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePhoneNumber(s *string) *OrderUpdate {
	if s != nil {
		ou.SetPhoneNumber(*s)
	}
	return ou
}

// SetEmail sets the "email" field.
func (ou *OrderUpdate) SetEmail(s string) *OrderUpdate {
	ou.mutation.SetEmail(s)
	return ou
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableEmail(s *string) *OrderUpdate {
	if s != nil {
		ou.SetEmail(*s)
	}
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(s string) *OrderUpdate {
	ou.mutation.SetStatus(s)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(s *string) *OrderUpdate {
	if s != nil {
		ou.SetStatus(*s)
	}
	return ou
}

// SetAmount sets the "amount" field.
func (ou *OrderUpdate) SetAmount(i int8) *OrderUpdate {
	ou.mutation.ResetAmount()
	ou.mutation.SetAmount(i)
	return ou
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableAmount(i *int8) *OrderUpdate {
	if i != nil {
		ou.SetAmount(*i)
	}
	return ou
}

// AddAmount adds i to the "amount" field.
func (ou *OrderUpdate) AddAmount(i int8) *OrderUpdate {
	ou.mutation.AddAmount(i)
	return ou
}

// SetErrorMessage sets the "error_message" field.
func (ou *OrderUpdate) SetErrorMessage(s string) *OrderUpdate {
	ou.mutation.SetErrorMessage(s)
	return ou
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableErrorMessage(s *string) *OrderUpdate {
	if s != nil {
		ou.SetErrorMessage(*s)
	}
	return ou
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ou *OrderUpdate) SetUserID(id int) *OrderUpdate {
	ou.mutation.SetUserID(id)
	return ou
}

// SetUser sets the "user" edge to the User entity.
func (ou *OrderUpdate) SetUser(u *User) *OrderUpdate {
	return ou.SetUserID(u.ID)
}

// AddValidationIDs adds the "validation" edge to the OrderValidation entity by IDs.
func (ou *OrderUpdate) AddValidationIDs(ids ...int) *OrderUpdate {
	ou.mutation.AddValidationIDs(ids...)
	return ou
}

// AddValidation adds the "validation" edges to the OrderValidation entity.
func (ou *OrderUpdate) AddValidation(o ...*OrderValidation) *OrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.AddValidationIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OrderUpdate) ClearUser() *OrderUpdate {
	ou.mutation.ClearUser()
	return ou
}

// ClearValidation clears all "validation" edges to the OrderValidation entity.
func (ou *OrderUpdate) ClearValidation() *OrderUpdate {
	ou.mutation.ClearValidation()
	return ou
}

// RemoveValidationIDs removes the "validation" edge to OrderValidation entities by IDs.
func (ou *OrderUpdate) RemoveValidationIDs(ids ...int) *OrderUpdate {
	ou.mutation.RemoveValidationIDs(ids...)
	return ou
}

// RemoveValidation removes "validation" edges to OrderValidation entities.
func (ou *OrderUpdate) RemoveValidation(o ...*OrderValidation) *OrderUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ou.RemoveValidationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.DepartureStation(); ok {
		if err := order.DepartureStationValidator(v); err != nil {
			return &ValidationError{Name: "departure_station", err: fmt.Errorf(`ent: validator failed for field "Order.departure_station": %w`, err)}
		}
	}
	if v, ok := ou.mutation.ArrivalStation(); ok {
		if err := order.ArrivalStationValidator(v); err != nil {
			return &ValidationError{Name: "arrival_station", err: fmt.Errorf(`ent: validator failed for field "Order.arrival_station": %w`, err)}
		}
	}
	if v, ok := ou.mutation.IDNumber(); ok {
		if err := order.IDNumberValidator(v); err != nil {
			return &ValidationError{Name: "id_number", err: fmt.Errorf(`ent: validator failed for field "Order.id_number": %w`, err)}
		}
	}
	if v, ok := ou.mutation.PhoneNumber(); ok {
		if err := order.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Order.phone_number": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Email(); ok {
		if err := order.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Order.email": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Amount(); ok {
		if err := order.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Order.amount": %w`, err)}
		}
	}
	if _, ok := ou.mutation.UserID(); ou.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.StartTime(); ok {
		_spec.SetField(order.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.EndTime(); ok {
		_spec.SetField(order.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.DepartureStation(); ok {
		_spec.SetField(order.FieldDepartureStation, field.TypeString, value)
	}
	if value, ok := ou.mutation.ArrivalStation(); ok {
		_spec.SetField(order.FieldArrivalStation, field.TypeString, value)
	}
	if value, ok := ou.mutation.IDNumber(); ok {
		_spec.SetField(order.FieldIDNumber, field.TypeString, value)
	}
	if value, ok := ou.mutation.PhoneNumber(); ok {
		_spec.SetField(order.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := ou.mutation.Email(); ok {
		_spec.SetField(order.FieldEmail, field.TypeString, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := ou.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt8, value)
	}
	if value, ok := ou.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt8, value)
	}
	if value, ok := ou.mutation.ErrorMessage(); ok {
		_spec.SetField(order.FieldErrorMessage, field.TypeString, value)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ou.mutation.ValidationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.RemovedValidationIDs(); len(nodes) > 0 && !ou.mutation.ValidationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.ValidationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetStartTime sets the "start_time" field.
func (ouo *OrderUpdateOne) SetStartTime(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetStartTime(t)
	return ouo
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStartTime(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetStartTime(*t)
	}
	return ouo
}

// SetEndTime sets the "end_time" field.
func (ouo *OrderUpdateOne) SetEndTime(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetEndTime(t)
	return ouo
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableEndTime(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetEndTime(*t)
	}
	return ouo
}

// SetDepartureStation sets the "departure_station" field.
func (ouo *OrderUpdateOne) SetDepartureStation(s string) *OrderUpdateOne {
	ouo.mutation.SetDepartureStation(s)
	return ouo
}

// SetNillableDepartureStation sets the "departure_station" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDepartureStation(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetDepartureStation(*s)
	}
	return ouo
}

// SetArrivalStation sets the "arrival_station" field.
func (ouo *OrderUpdateOne) SetArrivalStation(s string) *OrderUpdateOne {
	ouo.mutation.SetArrivalStation(s)
	return ouo
}

// SetNillableArrivalStation sets the "arrival_station" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableArrivalStation(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetArrivalStation(*s)
	}
	return ouo
}

// SetIDNumber sets the "id_number" field.
func (ouo *OrderUpdateOne) SetIDNumber(s string) *OrderUpdateOne {
	ouo.mutation.SetIDNumber(s)
	return ouo
}

// SetNillableIDNumber sets the "id_number" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableIDNumber(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetIDNumber(*s)
	}
	return ouo
}

// SetPhoneNumber sets the "phone_number" field.
func (ouo *OrderUpdateOne) SetPhoneNumber(s string) *OrderUpdateOne {
	ouo.mutation.SetPhoneNumber(s)
	return ouo
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePhoneNumber(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetPhoneNumber(*s)
	}
	return ouo
}

// SetEmail sets the "email" field.
func (ouo *OrderUpdateOne) SetEmail(s string) *OrderUpdateOne {
	ouo.mutation.SetEmail(s)
	return ouo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableEmail(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetEmail(*s)
	}
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(s string) *OrderUpdateOne {
	ouo.mutation.SetStatus(s)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetStatus(*s)
	}
	return ouo
}

// SetAmount sets the "amount" field.
func (ouo *OrderUpdateOne) SetAmount(i int8) *OrderUpdateOne {
	ouo.mutation.ResetAmount()
	ouo.mutation.SetAmount(i)
	return ouo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableAmount(i *int8) *OrderUpdateOne {
	if i != nil {
		ouo.SetAmount(*i)
	}
	return ouo
}

// AddAmount adds i to the "amount" field.
func (ouo *OrderUpdateOne) AddAmount(i int8) *OrderUpdateOne {
	ouo.mutation.AddAmount(i)
	return ouo
}

// SetErrorMessage sets the "error_message" field.
func (ouo *OrderUpdateOne) SetErrorMessage(s string) *OrderUpdateOne {
	ouo.mutation.SetErrorMessage(s)
	return ouo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableErrorMessage(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetErrorMessage(*s)
	}
	return ouo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ouo *OrderUpdateOne) SetUserID(id int) *OrderUpdateOne {
	ouo.mutation.SetUserID(id)
	return ouo
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OrderUpdateOne) SetUser(u *User) *OrderUpdateOne {
	return ouo.SetUserID(u.ID)
}

// AddValidationIDs adds the "validation" edge to the OrderValidation entity by IDs.
func (ouo *OrderUpdateOne) AddValidationIDs(ids ...int) *OrderUpdateOne {
	ouo.mutation.AddValidationIDs(ids...)
	return ouo
}

// AddValidation adds the "validation" edges to the OrderValidation entity.
func (ouo *OrderUpdateOne) AddValidation(o ...*OrderValidation) *OrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.AddValidationIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// ClearValidation clears all "validation" edges to the OrderValidation entity.
func (ouo *OrderUpdateOne) ClearValidation() *OrderUpdateOne {
	ouo.mutation.ClearValidation()
	return ouo
}

// RemoveValidationIDs removes the "validation" edge to OrderValidation entities by IDs.
func (ouo *OrderUpdateOne) RemoveValidationIDs(ids ...int) *OrderUpdateOne {
	ouo.mutation.RemoveValidationIDs(ids...)
	return ouo
}

// RemoveValidation removes "validation" edges to OrderValidation entities.
func (ouo *OrderUpdateOne) RemoveValidation(o ...*OrderValidation) *OrderUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouo.RemoveValidationIDs(ids...)
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.DepartureStation(); ok {
		if err := order.DepartureStationValidator(v); err != nil {
			return &ValidationError{Name: "departure_station", err: fmt.Errorf(`ent: validator failed for field "Order.departure_station": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.ArrivalStation(); ok {
		if err := order.ArrivalStationValidator(v); err != nil {
			return &ValidationError{Name: "arrival_station", err: fmt.Errorf(`ent: validator failed for field "Order.arrival_station": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.IDNumber(); ok {
		if err := order.IDNumberValidator(v); err != nil {
			return &ValidationError{Name: "id_number", err: fmt.Errorf(`ent: validator failed for field "Order.id_number": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.PhoneNumber(); ok {
		if err := order.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Order.phone_number": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Email(); ok {
		if err := order.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Order.email": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Amount(); ok {
		if err := order.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Order.amount": %w`, err)}
		}
	}
	if _, ok := ouo.mutation.UserID(); ouo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.StartTime(); ok {
		_spec.SetField(order.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.EndTime(); ok {
		_spec.SetField(order.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.DepartureStation(); ok {
		_spec.SetField(order.FieldDepartureStation, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ArrivalStation(); ok {
		_spec.SetField(order.FieldArrivalStation, field.TypeString, value)
	}
	if value, ok := ouo.mutation.IDNumber(); ok {
		_spec.SetField(order.FieldIDNumber, field.TypeString, value)
	}
	if value, ok := ouo.mutation.PhoneNumber(); ok {
		_spec.SetField(order.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Email(); ok {
		_spec.SetField(order.FieldEmail, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt8, value)
	}
	if value, ok := ouo.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt8, value)
	}
	if value, ok := ouo.mutation.ErrorMessage(); ok {
		_spec.SetField(order.FieldErrorMessage, field.TypeString, value)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouo.mutation.ValidationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.RemovedValidationIDs(); len(nodes) > 0 && !ouo.mutation.ValidationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.ValidationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   order.ValidationTable,
			Columns: []string{order.ValidationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordervalidation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
